version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-rs
    ports:
      - "27017:27017"
    command: --replSet rs0 --bind_ip_all
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
